---
title: "Cronograma"
toc: false
editor: source
---

*En construcción*

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(googlesheets4)
library(gt)
library(gtExtras)
library(tidyverse)
gs4_deauth()
d <- read_sheet("1gy7cqIeta23guGQqwOdKxbwO7rzhuato1bDejsCNwSg")
```

```{r, echo = FALSE}
d %>% 
  mutate(
    fecha = as.Date(fecha),
    lectura = ifelse(is.na(lectura), "", lectura),
    semana = ifelse(is.na(semana), "", semana),
    tema = ifelse(is.na(tema), "", tema)) %>%
  select(-semana) %>% 
  gt() %>%
    # text_transform(cells_body(columns = c(lectura)),
    #              fn = function(x){
    #                ifelse(is.na(x), fontawesome::fa('book', fill_opacity = 0.1), 
    #                       glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>"))
    #              }) %>%
  text_transform(cells_body(columns = c(slides)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('laptop', fill_opacity = 0.1), 
                          glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>"))
                 }) %>%
  text_transform(cells_body(columns = c(notas)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('laptop', fill_opacity = 0.1), 
                          glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>"))
                 }) %>%
  text_transform(cells_body(columns = c(tp)),
                 fn = function(x){
                   ifelse(is.na(x), fontawesome::fa('users', fill_opacity = 0.1),
                          glue::glue("<a href = {x}>{fontawesome::fa('users')}</a>"))
                   
                 }) %>%
  fmt_date(fecha, date_style = 28, locale = "es") %>%
  sub_missing(columns = fecha, missing_text = "") %>% 
  cols_width(
    fecha ~ px(60),
    tema ~ px(200),
    lectura ~ px(200),
    slides ~ px(60),
    notas ~ px(60),
    tp ~ px(60),
  )
```

